### ISSUE TITLE
Provide a free API call for the serialized buffer

### ISSUE THREAD

**Issue by tdenniston** [Shelnutt2/TileDB#10]
We can't depend on the user calling `free` on the pointer returned from `tiledb_query_serialize` as the allocator might be different. We should add something like `tiledb_query_serialize_free` for that purpose.

**Comment by Shelnutt2** [comment]
This is needed for the cases where tiledb itself allocates the buffer space and is not filling a preexisting user buffer.

**Comment by tdenniston** [comment]
Will be subsumed by https://github.com/TileDB-Inc/TileDB/issues/1214
