### ISSUE TITLE
Support Sparse Array Schema serialization

### ISSUE THREAD

**Issue by Shelnutt2** [Shelnutt2/TileDB#11]
Sparse Array Schema serialization is not currently supported. This issue is about adding sparse array schema serialization support. ~After support is added unit tests for sparse arrays should also be added. @tdenniston is working on refactoring the dense testing, check with him to understand how to apply his refactor to the `unit-capi-sparse_array.cc` to test serialization.~

Sparse arrays were blocked by the __coords attribute because previously `add_attribute` did not allow special attributes to be set.

Currently we check for [`__` (special_name_prefix)](https://github.com/Shelnutt2/TileDB/blob/98b4430cd1d6e73cf23c8363f9e807572df5cf48/tiledb/rest/capnp/array.cc#L648) .

The [add_attribute](https://github.com/Shelnutt2/TileDB/blob/98b4430cd1d6e73cf23c8363f9e807572df5cf48/tiledb/sm/array_schema/array_schema.cc#L432) was given a second parameter previously to allow for bypassing the special coordinate check.

If you remove the `special_name_prefix` check hopefully sparse arrays will just work. However its possible you'll discover other blockers. If so let's discuss what else needs changing.

**Comment by Shelnutt2** [comment]
@antalakas Since we saw that there is currently 0 unit tests for array schema serialization let's not include adding unit tests in this issue. It can be done in a follow up #12 .

**Comment by antalakas** [comment]
@Shelnutt2 since unit-capi-capnp.cc contains unit tests for dense array schema serialization, i am also adding sparse test method
