### ISSUE TITLE
Add unit tests for array schema serialization

### ISSUE THREAD

**Issue by Shelnutt2** [Shelnutt2/TileDB#12]
Add unit tests for array schema serialization. Currently there is an [unit-capi-array_schema.cc](https://github.com/Shelnutt2/TileDB/blob/dev/test/src/unit-capi-array_schema.cc) which has various tests for array schemas. We need to modify this test to add support for serialization. You should be able to create shims for the various array schema operations like @tdenniston did for dense.

Here is the PR where @tdenniston add shims for serialization so we can use a single dense unit test query file but test both serialize and none serialize version: https://github.com/Shelnutt2/TileDB/pull/13/files

First I'd look at `unit-capi-array_schema.cc` and create a list of the functions you think we should add shims to to test the serialization. For querying it was just `submit` and `finalize`, for array schema it will probably be `load`, `create`, etc.

After `unit-capi-array_schema.cc` is updated we can safely remove the `unit-capi-capnp.cc` file as it will be superseeded.

**Comment by antalakas** [comment]
Should we use different test files for dense /sparse schema testing?

**Comment by Shelnutt2** [comment]
@antalakas I think this single file is sufficient, it has two tests for the sparse case. The main difference, specifically in terms of the array schemas, between dense and sparse is *after* the first write has happened the sparse array schema will now have 1 addition attribute of the `__coords`. Besides that they are identical for everything else that will involve serialization of the array schema itself.

**Comment by antalakas** [comment]
@Shelnutt2, i added shims for `tiledb_array_create` and `tiledb_array_schema_load`.  I am replacing calls to `tiledb_array_create` with the wrapper function. For some of them it works, but for others an error happens here:

https://github.com/Shelnutt2/TileDB/blob/9d1d93846b245964b34d5c6d4a4b9fc7cba052e3/tiledb/rest/capnp/array.cc#L564

This goes wrong because the domain is null.  

`tiledb_array_get_schema` is also a candidate

**Comment by Shelnutt2** [comment]
@antalakas why are the domains null? Is it part of the specific tests where something is done before setting the done and a failures is expected? Or is this an issue with serialization and the domain get lost/dropped for some reason?

**Comment by antalakas** [comment]
@Shelnutt2, It is part of the specific test
