### ISSUE TITLE
Support tiledb:// uri scheme

### ISSUE THREAD

**Issue by Shelnutt2** [Shelnutt2/TileDB#33]
We've decided that `tiledb://<namespace>/<array_name>` should be the uri scheme used for access remote arrays. Instead of relying only on the rest server parameters to be set we should just add a vfs check for `tiledb://`. Drop the organization config parameter.

Like today I believe we want to allow array creation by using `tiledb://<namespace>/<array_uri>` when a new array is being created.

Further bonus is supporting `tiledb://<username>:<password>@<rest_server>/<namespace>/<array>`
Also inplace of `<username>/<password>` -> `<api_token>` should be supported.

Summary:
`tiledb://<namespace>/<array_name>`
`tiledb://<namespace>/<array_uri>`
 `tiledb://<username>:<password>@<rest_server>/<namespace>/<array>`
`tiledb://<api_token>@<rest_server>/<namespace>/<array>`

**Comment by tdenniston** [comment]
For now we won't support auth or rest server address via the URI.
